
//Hardcoded job data
export const jobs = [
    {
        id: 1, 
        title: "Frontend Developer", 
        company: "Google",
        location: "Mountain View, CA", 
        salary: "$120,000",
        description: "Google is looking for a frontend developer to join our team.",
        tags: ["React, Angular, Vue.js, JavaScript, Remote, Full-time"],
        requirements: ["2+ years of experience", "Bachelor's degree in Computer Science", "Experience with React, Angular, and Vue.js", "Strong knowledge of JavaScript and CSS"],
        postedDate: "2024-02-01",
    },
    { 
        id: 2, 
        title: "Backend Developer", 
        company: "Facebook", 
        location: "Menlo Park, CA", 
        salary: "$130,000",
        description: "Facebook is looking for a backend developer to join our team.",
        tags: ["Node.js, Python, Ruby on Rails, JavaScript, Remote, Full-time"],
        requirements: ["3+ years of experience", "Bachelor's degree in Computer Science","Strong knowledge of RESTful APIs"],
        postedDate: "2024-03-22",
    },
    { 
        id: 3, 
        title: "Fullstack Developer", 
        company: "Amazon", 
        location: "Seattle, WA", 
        salary: "$140,000",
        description: "Amazon is looking for a fullstack developer to join our team.",
        tags: ["React, Node.js, MongoDB, JavaScript, Remote"],
        requirements: ["5+ years of experience", "Bachelor's degree in Computer Science","Experience with React, Node.js, and MongoDB"],
        postedDate: "2024-05-12",
    },
    { 
        id: 4, 
        title: "DevOps Engineer", 
        company: "Microsoft", 
        location: "Redmond, WA", 
        salary: "$150,000",
        description: "Microsoft is looking for a DevOps engineer to join our team.",
        tags: ["Docker, Kubernetes, Jenkins, Remote, Full-time"],
        requirements: ["4+ years of experience", "Bachelor's degree in Software Engineering","Experience with AWS, Azure, or GCP"],
        postedDate: "2024-07-10",
    },
    { 
        id: 5, 
        title: "Data Scientist", 
        company: "Apple", 
        location: "Cupertino, CA", 
        salary: "$160,000",
        description: "Apple is looking for a data scientist to join our team.",
        tags: ["Python, R, SQL, Remote, Full-time"],
        requirements: ["3+ years of experience", "Bachelor's degree in Computer Science","Strong knowledge of statistics and machine learning"],
        postedDate: "2024-08-01",
    },
    { 
        id: 6, 
        title: "Machine Learning Engineer", 
        company: "Tesla", 
        location: "Palo Alto, CA", 
        salary: "$170,000",
        description: "Tesla is looking for a machine learning engineer to join our team.",
        tags: ["TensorFlow, Python, Data Science, Full-time"],
        requirements: ["2+ years of experience", "Bachelor's degree in Computer Engineering", "Strong knowledge of statistics and machine learning"],
        postedDate: "2025-02-24",
    },
    { 
        id: 7, 
        title: "Software Engineer", 
        company: "Netflix", 
        location: "Los Gatos, CA", 
        salary: "$180,000",
        description: "Netflix is looking for a software engineer to join our team.",
        tags: ["Java, C++, Python, Remote, Full-time"],
        requirements: ["3+ years of experience", "Bachelor's degree in Software Engineering","Strong knowledge of algorithms and data structures"],
        postedDate: "2025-02-15",},
    { 
        id: 8, 
        title: "QA Engineer", 
        company: "Uber", 
        location: "San Francisco, CA", 
        salary: "$190,000",
        description: "Uber is looking for a QA engineer to join our team.",
        tags: ["Selenium, JUnit, TestNG, Remote, Full-time"],
        requirements: ["3+ years of experience", "Bachelor's degree in Computer Science","Strong knowledge of software testing methodologies"],
        postedDate: "2025-01-01",
    },
    { 
        id: 9, 
        title: "Security Engineer", 
        company: "Lyft", 
        location: "San Francisco, CA", 
        salary: "$200,000",
        description: "Lyft is looking for a security engineer to join our team.",
        tags: ["OWASP, NIST, ISO 27001, Remote, Full-time"],
        requirements: ["3+ years of experience", "Bachelor's degree in Cyber Security", "Experience with Git and GitHub"],
        postedDate: "2024-12-24",
    },
    { 
        id: 10, 
        title: "Product Manager", 
        company: "Airbnb", 
        location: "San Francisco, CA", 
        salary: "$210,000",
        description: "Airbnb is looking for a product manager to join our team.",
        tags: ["Agile, Scrum, Kanban, Remote, Full"],
        requirements: ["2+ years of experience", "Bachelor's degree in Computer Engineering", "Strong knowledge of product management best practices"],
        postedDate: "2024-10-01",
    }
];


export default jobs;